version: "3.8"

services:
  postgres:
    image: postgres:15-alpine
    container_name: fintar_postgres
    environment:
      POSTGRES_DB: fintar_db
      POSTGRES_USER: fintar_user
      POSTGRES_PASSWORD: fintar_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init-scripts:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U fintar_user -d fintar_db"]
      interval: 30s
      timeout: 10s
      retries: 3

  mongodb:
    image: mongo:7-jammy
    container_name: fintar_mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: fintar_admin
      MONGO_INITDB_ROOT_PASSWORD: fintar_password
      MONGO_INITDB_DATABASE: fintar_ai
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
      - ./mongodb/init:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 30s
      timeout: 10s
      retries: 3

  redis:
    image: redis:7-alpine
    container_name: fintar_redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  postgres_data:
  mongodb_data:
  redis_data:
